language: node_js
node_js:
- '0.10'
before_script:
- "./node_modules/.bin/grunt ci-init"
script: "./node_modules/.bin/grunt ci"
before_install:
- openssl aes-256-cbc -K $encrypted_4adc289ae43c_key -iv $encrypted_4adc289ae43c_iv
  -in .coveralls.yml.enc -out .coveralls.yml -d
